-- ADAMA Production BI — Sprint 5.1 Cloud Schema
-- Run once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists facilities (
  id text primary key,
  name text not null,
  unit text default 'ליטר',
  target_type text default 'daily',
  production_target numeric default 0,
  packaging_target numeric default 0,
  active boolean default true,
  display_order int default 0,
  updated_at timestamptz default now()
);

create table if not exists packaging_lines (
  id text primary key,
  name text not null,
  daily_target numeric default 0,
  unit text default 'ליטר',
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists production_entries (
  id text primary key,
  date date,
  facility text,
  packaging_line text,
  shift text,
  production numeric default 0,
  packaging numeric default 0,
  order_no text,
  batch text,
  note text,
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists quality_entries (
  id text primary key,
  date date,
  facility text,
  order_no text,
  batch text,
  material text,
  inspection_lot text,
  status text default 'ok',
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists events (
  id text primary key,
  date date,
  facility text,
  event_type text default 'other',
  title text,
  description text,
  severity text default 'medium',
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists app_users (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  full_name text,
  role text default 'viewer',
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists app_audit_log (
  id bigint generated by default as identity primary key,
  at timestamptz default now(),
  user_email text,
  action text,
  entity text,
  entity_id text,
  details jsonb
);

insert into facilities (id, name, unit, target_type, production_target, packaging_target, active, display_order)
values
('1543','מתקן 1543','ליטר','packagingLines',0,0,true,1),
('1542','מתקן 1542','ליטר','packagingLines',0,0,true,2),
('1541','מתקן 1541','ליטר','monthly',210000,210000,true,3),
('1540','מתקן 1540','ק״ג','daily',18000,18000,true,4),
('1528','מתקן 1528','ליטר','daily',80000,80000,true,5),
('1525','מתקן 1525','ליטר','monthly',130000,130000,true,6),
('1524','מתקן 1524','ליטר','daily',6000,6000,true,7),
('1523','מתקן 1523','ליטר','daily',40000,40000,true,8),
('1521','מתקן 1521','ליטר','daily',0,0,true,9),
('1519','מתקן 1519','ק״ג','daily',0,0,true,10)
on conflict (id) do update set
  name = excluded.name,
  unit = excluded.unit,
  target_type = excluded.target_type,
  production_target = excluded.production_target,
  packaging_target = excluded.packaging_target,
  active = excluded.active,
  display_order = excluded.display_order,
  updated_at = now();

insert into packaging_lines (id, name, daily_target, unit, active)
values
('1L','קו 1 ליטר',18000,'ליטר',true),
('5L','קו 5 ליטר',60000,'ליטר',true),
('10_20L','קו 10/20 ליטר',60000,'ליטר',true)
on conflict (id) do update set
  name = excluded.name,
  daily_target = excluded.daily_target,
  unit = excluded.unit,
  active = excluded.active,
  updated_at = now();

alter table facilities enable row level security;
alter table packaging_lines enable row level security;
alter table production_entries enable row level security;
alter table quality_entries enable row level security;
alter table events enable row level security;
alter table app_users enable row level security;
alter table app_audit_log enable row level security;

drop policy if exists "bi public all facilities" on facilities;
create policy "bi public all facilities" on facilities for all using (true) with check (true);

drop policy if exists "bi public all packaging_lines" on packaging_lines;
create policy "bi public all packaging_lines" on packaging_lines for all using (true) with check (true);

drop policy if exists "bi public all production_entries" on production_entries;
create policy "bi public all production_entries" on production_entries for all using (true) with check (true);

drop policy if exists "bi public all quality_entries" on quality_entries;
create policy "bi public all quality_entries" on quality_entries for all using (true) with check (true);

drop policy if exists "bi public all events" on events;
create policy "bi public all events" on events for all using (true) with check (true);

drop policy if exists "bi public all app_users" on app_users;
create policy "bi public all app_users" on app_users for all using (true) with check (true);

drop policy if exists "bi public all app_audit_log" on app_audit_log;
create policy "bi public all app_audit_log" on app_audit_log for all using (true) with check (true);
