-- ADAMA Production BI - Supabase Schema
-- Run this in Supabase SQL Editor.

create table if not exists facilities (
  id text primary key,
  name text not null,
  unit text default 'ליטר',
  target_type text default 'daily',
  production_target numeric default 0,
  packaging_target numeric default 0,
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists packaging_lines (
  id text primary key,
  name text not null,
  daily_target numeric default 0,
  unit text default 'ליטר',
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists production_entries (
  id text primary key,
  date date,
  facility text,
  packaging_line text,
  shift text,
  production numeric default 0,
  packaging numeric default 0,
  order_no text,
  batch text,
  note text,
  source text,
  created_at timestamptz default now()
);

create table if not exists quality_entries (
  id text primary key,
  date date,
  facility text,
  order_no text,
  batch text,
  material text,
  inspection_lot text,
  status text,
  source text,
  created_at timestamptz default now()
);

create table if not exists app_audit_log (
  id bigint generated by default as identity primary key,
  at timestamptz default now(),
  action text,
  entity text,
  details jsonb
);

insert into facilities (id, name, unit, target_type, production_target, packaging_target, active)
values
('1543','מתקן 1543','ליטר','packagingLines',0,0,true),
('1542','מתקן 1542','ליטר','packagingLines',0,0,true),
('1541','מתקן 1541','ליטר','monthly',210000,210000,true),
('1540','מתקן 1540','ק״ג','daily',18000,18000,true),
('1528','מתקן 1528','ליטר','daily',80000,80000,true),
('1525','מתקן 1525','ליטר','monthly',130000,130000,true),
('1524','מתקן 1524','ליטר','daily',6000,6000,true),
('1523','מתקן 1523','ליטר','daily',40000,40000,true),
('1521','מתקן 1521','ליטר','daily',0,0,true),
('1519','מתקן 1519','ק״ג','daily',0,0,true)
on conflict (id) do nothing;

insert into packaging_lines (id, name, daily_target, unit, active)
values
('1L','קו 1 ליטר',18000,'ליטר',true),
('5L','קו 5 ליטר',60000,'ליטר',true),
('10_20L','קו 10/20 ליטר',60000,'ליטר',true)
on conflict (id) do nothing;

-- Simple demo policy for early testing only:
-- In production, enable authentication and replace these policies.
alter table facilities enable row level security;
alter table packaging_lines enable row level security;
alter table production_entries enable row level security;
alter table quality_entries enable row level security;
alter table app_audit_log enable row level security;

drop policy if exists "public read facilities" on facilities;
create policy "public read facilities" on facilities for select using (true);
drop policy if exists "public write facilities" on facilities;
create policy "public write facilities" on facilities for all using (true) with check (true);

drop policy if exists "public read packaging lines" on packaging_lines;
create policy "public read packaging lines" on packaging_lines for select using (true);
drop policy if exists "public write packaging lines" on packaging_lines;
create policy "public write packaging lines" on packaging_lines for all using (true) with check (true);

drop policy if exists "public read production entries" on production_entries;
create policy "public read production entries" on production_entries for select using (true);
drop policy if exists "public write production entries" on production_entries;
create policy "public write production entries" on production_entries for all using (true) with check (true);

drop policy if exists "public read quality entries" on quality_entries;
create policy "public read quality entries" on quality_entries for select using (true);
drop policy if exists "public write quality entries" on quality_entries;
create policy "public write quality entries" on quality_entries for all using (true) with check (true);

drop policy if exists "public read audit" on app_audit_log;
create policy "public read audit" on app_audit_log for select using (true);
drop policy if exists "public write audit" on app_audit_log;
create policy "public write audit" on app_audit_log for insert with check (true);
